MODULE_NAME:= axi_exported
include /wdc/proj/cto/top/work/rasmus.madsen/cto/main/util/build/pre.mk
TB_TOP := axi_tb_top
IP_FILELIST +=  \/wdc/proj/cto/top/work/rasmus.madsen/cto/main/joboutput/export/axi.f
include /wdc/proj/cto/top/work/rasmus.madsen/cto/main/util/build/post.mk
